info:
  name: eureka client
  groupId: com.szss
  artifactId: eureka-client
  version: 1.0-SNAPSHOT

server:
  port: 8888

spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka,http://127.0.0.1:8763/eureka
