info:
  name: eureka client
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

server:
  port: 8888

spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka,http://127.0.0.1:8763/eureka
