info:
  name: eureka client
  groupId: com.szss
  artifactId: users-service
  version: 1.0-SNAPSHOT

server:
  port: 8000

spring:
  application:
    name: users-service
  profiles:
    active: dev

---
spring:
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
